# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4
      - image: image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            export FLASK_DEBUG=0
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
     - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
     - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
     - run:
          name: Install npm dependencies.
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: build/migrate all the things.
          command: |
            npm run build
            flask db init
            flask db migrate
            flask db upgrade
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flask test
      - run:
          name: run flask
          command: flask run

      - store_artifacts:
          path: test-reports
          destination: test-reports
